apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-devops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omar-ghaly/Cloud-DevOps-Project.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
