apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloud-devops-eks
  region: us-east-1
  version: "1.32"

iam:
  withOIDC: true

vpc:
  autoAllocateIPv6: false
  nat:
    gateway: Single

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: omar-key
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true

addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: metrics-server
    version: latest
