plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  instance-id: i-07f6eb472aaabea1c

compose:
  ansible_host: public_ip_address

keyed_groups:
  - key: tag:Name
    prefix: ''
    separator: ''

hostnames:
  - tag:Name
